Modifs en rapport avec la base de donnees
Jai ajoute des lignes pour Objectify dans le web.xml
Jai enleve les commentaires qui permettaient avant de ne pas faire appel
a la bd, pour tester avec la bd.
Ca na pas marche. Pour linstant quand je fais appel a findByEmail de
DAOUser, jobtiens une exception (Caused by:
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0).